service: serverless-webpack-typescript-example
frameworkVersion: '2.61.0'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
functions:
  helloAsync:
    handler: handler.helloAsync
    events:
      - http:
          method: get
          path: hello-async
          integration: lambda
  helloCb:
    handler: handler.helloCb
    events:
      - http:
          method: get
          path: hello-cb
          integration: lambda