service: serverless-webpack-typescript-example
frameworkVersion: '2.61.0'

# Add the serverless-webpack plugin
plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
  
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  environment:
    FIREBASE_CREDENTIALS: ${ssm:/FIREBASE_CREDENTIALS}

functions:
  getPresignedURL:
    handler: controllers/images.getPresignedURL
    events:
      - httpApi:
          method: get
          path: images/presigned-url
          integration: lambda